services:
  calendar-service:
    container_name: "calendar"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8880:8880"
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/calendar_db
      - spring.datasource.username=admin
      - spring.datasource.password=admin
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.username=admin
      - spring.rabbitmq.password=admin
      - update.calendar.scheduler=0 * * * * *
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres
    environment:
      POSTGRES_DB: calendar_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
